repos:
  # - repo: https://github.com/psf/black
  #   rev: 23.9.1
  #   hooks:
  #     - id: black
  #       language_version: python3.11

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       name: flake8
  #       types: [python]
  #       args:
  #       -  --max-line-length=88
  #       -  --ignore=E203,E501,W503


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.1.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python]

      - id: ruff-format
