[tool.ruff]
line-length = 80
exclude = [
        "migrations",
]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.djlint]
indent=4
blank_line_after_tag="load,extends,include"
close_void_tags=true

format_js=true
format_css=true

[tool.djlint.css]
indent_size=2

[tool.djlint.js]
indent_size=2
